name: Add Github Token To Environment
author: John Gicharu
description: GitHub Action for building and releasing Electron apps

inputs:
  github_token:
    description: GitHub authentication token
    required: true

runs:
  using: node18
  main: actions.js
