name: CI ALL
on: [push]

jobs:
  build:
    name: Build Gosuto
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: 'ls '
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: machine echo $HOME
        run: 'echo $HOME'
      - name: Install dependencies
        run: yarn || "ls"
      - name: Build
        run: yarn package
